services:
  app:
    container_name: z-mirror
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      EXPOSE "80"
      EXPOSE "8080"
      EXPOSE "8070"
      EXPOSE "8090"
